// src/components/aggregations/Structure.tsx
import { For } from 'solid-js'
import type { Schema, Update } from '../../schema'
import { Chameleon } from '../Chameleon'
import { Delta } from '../../delta'

export function Structure<T>(props: {
	value: T,
	fields: Record<string, Schema<T>>,
	onUpdate: (update: Update<T>) => void,
}) {
	return <div class="vbox">
		<For each={Object.keys(props.fields)}>{key => <Chameleon
			type={props.fields[key]}
			value={(props.value as any)[key]}
			onUpdate={update => props.onUpdate({
				...update,
				delta: { [key]: update.delta } as Delta<T>,
			})}
		/>}</For>
	</div>
}

// src/components/aggregations/Structure.vue
<script setup lang="ts">
import type { Schema } from '../../schema'
import Chameleon from '../Chameleon.vue'

const props = defineProps<{
	value: any,
	fields: Record<string, Schema<any>>,
}>()
</script>

<template>
	<Chameleon v-for="(field, key) in fields" :type="field" :value="value[key]" @update="$emit('update', ...$event)" />
</template>

<style lang="scss">
.chameleon {
	flex-direction: column;
}
</style>
