// src/components/basic-controls/ListView.tsx
import { Grip } from './Grip'
import { useEnabled } from '../Enable'
import { Component, createMemo, createSignal, For } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { createStore2 } from '../../composables'
import { TextBox } from './TextBox'
import './ListView.scss'
import { isEmpty } from '../../utilities'

export interface ListViewDescriptor<T, ColumnID extends string = string> {
	getKey: (item: T) => PropertyKey,
	/**
	 * If getChildren returns non-empty arrays, ListView acts as a tree view.
	 */
	getChildren?: (item: T) => T[],
	/**
	 * Get the text for filtering.
	 * Usually, not all fields should be used for filtering.
	 * It is recommended that multiple fields are joined with newlines.
	 * Filtering is required for consistency; also because the <input> is what possesses the focus all the time.
	 */
	getPlainText: (item: T) => string,
	columns: { [id in ColumnID]: {
		render: Component<{ item: T }>,
		name: string,
		/** If the compare key is not passed in, the column is not sortable. */
		compareKey?: (item: T) => number | string,
		initialWidth: number,
	} },
}

interface Row<T> {
	key: PropertyKey,
	/** The original data passed in for this row. */
	item: T,
	/** The depth of the row (if nested or grouped) relative to the root row array. */
	indent: number,
	children: Row<T>[],
}

/**
 * This is a versatile component that covers controls ranging from list boxes to tree views.
 */
// The internal data structure is heavily inspired by TanStack Table.
// https://tanstack.com/table/v8/docs/guide/row-models
// Grouping is omitted because it is incompatible with a tree.
export function ListView<T, ColumnID extends string>(props: {
	items: T[],
	view: ListViewDescriptor<T, ColumnID>,
	multipleSelection?: boolean,
	dragDrop?: boolean,
}) {
	//============================================================================
	// Convert data into internal representation
	//============================================================================

	//----------------------------------------------------------------------------
	// From items to rows

	const allRows = createMemo(() => {
		return function traverse(items: T[], depth: number): Row<T>[] {
			return items.map(item => ({
				key: props.view.getKey(item),
				item,
				indent: depth,
				children: traverse(props.view.getChildren?.(item) ?? [], depth + 1),
			}))
		}(props.items, 0)
	})

	//----------------------------------------------------------------------------
	// Apply text filter

	const [filter, setFilter] = createSignal('')
	let filterInput!: HTMLInputElement

	const filterRow = (row: Row<T>): boolean => (props.view.getPlainText ?? props.view.getKey)(row.item)
		.toString().includes(filter())

	const filteredRows = createMemo(() => {
		if (!allRows().length || !filter()) return allRows()
		return function traverse(rows: Row<T>[]): Row<T>[] {
			return rows.flatMap(row => {
				const children = traverse(row.children)
				return children.length || filterRow(row)
					? [{ ...row, children }]
					: []
			})
		}(allRows())
	})

	//----------------------------------------------------------------------------
	// Apply sorting

	const [sorting, setSorting] = createStore2<{ by: ColumnID, descending: boolean }[]>([])
	const sortingMap = createMemo(() => {
		const result: { [id in ColumnID]?: { order: number, clause: { descending: boolean } } } = {}
		for (const [order, clause] of sorting.entries()) {
			result[clause.by as ColumnID] = { order, clause }
		}
		return result
	})

	const compareRows = (a: Row<T>, b: Row<T>): number => {
		for (const { by, descending } of sorting) {
			const { compareKey } = props.view.columns[by as ColumnID]
			if (!compareKey) continue
			const ka = compareKey(a.item)
			const kb = compareKey(b.item)
			if (ka === kb) continue
			if (typeof ka === typeof kb) return (ka < kb) !== descending ? -1 : 1
			// Syntax highlight breaks if the following line is uncommented.
			// return (typeof ka < typeof kb) !== descending ? -1 : 1
		}
		return 0
	}

	const sortedRows = createMemo(() => {
		if (!filteredRows().length || !sorting.length) return filteredRows()
		return function traverse(rows: Row<T>[]): Row<T>[] {
			return rows.map(row => ({
				...row,
				children: traverse(row.children),
			})).sort(compareRows)
		}(filteredRows())
	})

	function clickHeader(columnID: ColumnID, multipleSelection: boolean) {
		setSorting(sorting => {
			if (multipleSelection) {
				const clause = sortingMap()[columnID]?.clause
				if (clause) {
					clause.descending = !clause.descending
				} else {
					sorting.push({
						by: columnID,
						descending: false,
					})
				}
			} else {
				if (sorting.length === 1 && sorting[0].by === columnID) {
					const clause = sorting[0]
					if (clause.descending) {
						sorting.pop()
					} else {
						clause.descending = true
					}
				} else {
					sorting.splice(0, Infinity, {
						by: columnID,
						descending: false,
					})
				}
			}
		})
	}

	//----------------------------------------------------------------------------
	// Flat out expanded rows

	const [expanded, setExpanded] = createStore2<Record<PropertyKey, true>>({})
	const [expandedInverted, setExpandedInverted] = createSignal(false)
	const isExpanded = (key: PropertyKey) => !!expanded[key] !== expandedInverted()
	const toggleExpanded = (key: PropertyKey, newValue?: boolean) => {
		if (newValue === undefined ? expanded[key] : newValue === expandedInverted()) {
			setExpanded(expanded => delete expanded[key])
		} else {
			setExpanded(expanded => expanded[key] = true)
		}
	}
	const expandedRows = createMemo(() => {
		if (
			!sortedRows().length
			|| isEmpty(expanded) && !expandedInverted()
			|| !props.view.getChildren
		) return sortedRows()
		const result: Row<T>[] = []
		return (function traverse(rows: Row<T>[]) {
			for (const row of rows) {
				result.push(row)
				if (isExpanded(row.key)) traverse(row.children)
			}
			return result
		})(sortedRows())
	})

	//----------------------------------------------------------------------------
	// Hide data too big
	// This is the final data source for display.

	const visibleRows = createMemo(() => {
		if (expandedRows().length <= 1000) return expandedRows()
		return expandedRows().slice(0, 1000)
	})

	//============================================================================
	// Miscellaneous processing not directly related to data
	//============================================================================

	//----------------------------------------------------------------------------
	// Enabled

	const enabled = useEnabled()

	//----------------------------------------------------------------------------
	// Column reordering

	const [visibleColumns, setVisibleColumns] = createStore2(Object.keys(props.view.columns) as ColumnID[])

	//----------------------------------------------------------------------------
	// Column resizing

	const [columnWidth, setColumnWidth] = createStore2<{ [id in ColumnID]?: number }>({})
	const gridTemplateColumns = createMemo(() => visibleColumns.map(id =>
		(columnWidth[id] ?? props.view.columns[id].initialWidth) + 'px'
	).join(' '))

	//----------------------------------------------------------------------------
	// Selection

	// const modelValue = defineModel<number>({ default: 0 }) // currentIndex
	// const selectionStart = ref(2)
	// const selectionEnd = ref(4)

	return <div class="list-view vbox" classList={{
		tree: !!props.view.getChildren,
	}} onMouseDown={event => {
		if (!enabled()) return
		if (event.target !== filterInput) {
			event.preventDefault()
			filterInput.focus()
		}
	}}>
		<TextBox ref={filterInput} value={filter()} onUpdate={setFilter} />
		<table class="vbox fill scroll" style={{
			'grid-template-columns': gridTemplateColumns(),
		}} inert={!enabled}>
			<thead>
				<tr classList={{
					expanded: expandedInverted(),
				}}>
					<For each={visibleColumns}>{columnID => <th class="hbox" classList={{
						ascending: sortingMap()[columnID]?.clause.descending === false,
						descending: sortingMap()[columnID]?.clause.descending === true,
					}} data-sort-order={sortingMap()[columnID]?.order} onClick={event =>
						(event.target as HTMLElement).classList.contains('grip')
						|| clickHeader(columnID, event.ctrlKey || event.metaKey)}>
						<span class="fill ellipsis">{props.view.columns[columnID].name}</span>
						<Grip x={columnWidth[columnID] ?? props.view.columns[columnID].initialWidth} minX={0} onUpdate={x => setColumnWidth(columnWidth => columnWidth[columnID] = x)} />
					</th>}</For>
				</tr>
			</thead>
			<tbody>
				<For each={visibleRows()}>{row => <tr classList={{
					// current: i === modelValue,
					// selected: i >= selectionStart && i < selectionEnd,
					expandable: !!row.children.length,
					expanded: !!row.children.length && isExpanded(row.key),
				}} style={{
					'--indent': row.indent,
				}} onClick={() => toggleExpanded(row.key)}>
					<For each={visibleColumns}>{columnID => <td class="ellipsis">
						<Dynamic component={props.view.columns[columnID].render} item={row.item} />
					</td>}</For>
				</tr>}</For>
			</tbody>
		</table>
	</div>
}

// src/components/basic-controls/ListView.vue
<!--
	This is a versatile component that covers controls ranging from list boxes to tree views.
	The internal data structure is heavily inspired by TanStack Table.
	https://tanstack.com/table/v8/docs/guide/row-models
	Grouping is omitted because it is incompatible with a tree.
-->

<script lang="ts" setup generic="T, ColumnID extends string">
import { computed, ref, type Component } from 'vue'
import Grip from './Grip.vue'
import { useEnabled } from '../Enable.vue';

export interface ListViewDescriptor<T, ColumnID extends string = string> {
	getKey: (item: T) => PropertyKey,
	/**
	 * If getChildren returns non-empty arrays, ListView acts as a tree view.
	 */
	getChildren?: (item: T) => T[],
	/**
	 * Get the text for filtering.
	 * Usually, not all fields should be used for filtering.
	 * It is recommended that multiple fields are joined with newlines.
	 * Filtering is required for consistency; also because the <input> is what possesses the focus all the time.
	 */
	getPlainText: (item: T) => string,
	columns: { [id in ColumnID]: {
		render: Component<{ item: T }>,
		name: string,
		/** If the compare key is not passed in, the column is not sortable. */
		compareKey?: (item: T) => number | string,
		initialWidth: number,
	} },
}

const props = defineProps<{
	items: T[],
	view: ListViewDescriptor<T, ColumnID>,
	multipleSelection?: boolean,
	dragDrop?: boolean,
}>()

//============================================================================
// Convert data into internal representation
//============================================================================

interface Row<T> {
	key: PropertyKey,
	/** The original data passed in for this row. */
	item: T,
	/** The depth of the row (if nested or grouped) relative to the root row array. */
	indent: number,
	children: Row<T>[],
}

//----------------------------------------------------------------------------
// From items to rows

const allRows = computed(() => {
	return function traverse(items: T[], depth: number): Row<T>[] {
		return items.map(item => ({
			key: props.view.getKey(item),
			item,
			indent: depth,
			children: traverse(props.view.getChildren?.(item) ?? [], depth + 1),
		}))
	}(props.items, 0)
})

//----------------------------------------------------------------------------
// Apply text filter

const filter = ref('')
const filterInput = ref<HTMLInputElement>()

const filterRow = (row: Row<T>): boolean => (props.view.getPlainText ?? props.view.getKey)(row.item)
	.toString().includes(filter.value)

const filteredRows = computed(() => {
	if (!allRows.value.length || !filter.value) return allRows.value
	return function traverse(rows: Row<T>[]): Row<T>[] {
		return rows.flatMap(row => {
			const children = traverse(row.children)
			return children.length || filterRow(row)
				? [{ ...row, children }]
				: []
		})
	}(allRows.value)
})

//----------------------------------------------------------------------------
// Apply sorting

const sorting = ref<{ by: ColumnID, descending: boolean }[]>([])
const sortingMap = computed(() => {
	const result: { [id in ColumnID]?: { order: number, clause: { descending: boolean } } } = {}
	for (const [order, clause] of sorting.value.entries()) {
		result[clause.by as ColumnID] = { order, clause }
	}
	return result
})

const compareRows = (a: Row<T>, b: Row<T>): number => {
	for (const { by, descending } of sorting.value) {
		const { compareKey } = props.view.columns[by as ColumnID]
		if (!compareKey) continue
		const ka = compareKey(a.item)
		const kb = compareKey(b.item)
		if (ka === kb) continue
		if (typeof ka === typeof kb) return (ka < kb) !== descending ? -1 : 1
		// return (typeof ka < typeof kb) !== descending ? -1 : 1
	}
	return 0
}

const sortedRows = computed(() => {
	if (!filteredRows.value.length || !sorting.value.length) return filteredRows.value
	return function traverse(rows: Row<T>[]): Row<T>[] {
		return rows.map(row => ({
			...row,
			children: traverse(row.children),
		})).sort(compareRows)
	}(filteredRows.value)
})

function clickHeader(columnID: ColumnID, multipleSelection: boolean) {
	if (multipleSelection) {
		const clause = sortingMap.value[columnID]?.clause
		if (clause) {
			clause.descending = !clause.descending
		} else {
			sorting.value.push({
				// @ts-expect-error UnwrapRef<ColumnID> does not understand generic…?
				by: columnID,
				descending: false,
			})
		}
	} else {
		if (sorting.value.length === 1 && sorting.value[0].by === columnID) {
			const clause = sorting.value[0]
			if (clause.descending) {
				sorting.value.pop()
			} else {
				clause.descending = true
			}
		} else {
			sorting.value.splice(0, Infinity, {
				// @ts-expect-error Ditto.
				by: columnID,
				descending: false,
			})
		}
	}
}

//----------------------------------------------------------------------------
// Flat out expanded rows

const expanded = ref(new Set<PropertyKey>)
const expandedInverted = ref(false)
const isExpanded = (key: PropertyKey) => expanded.value.has(key) !== expandedInverted.value
const toggleExpanded = (key: PropertyKey, newValue?: boolean) => {
	if (newValue === undefined ? expanded.value.has(key) : newValue === expandedInverted.value) {
		expanded.value.delete(key)
	} else {
		expanded.value.add(key)
	}
}
const expandedRows = computed(() => {
	if (
		!sortedRows.value.length
		|| !expanded.value.size && !expandedInverted.value
		|| !props.view.getChildren
	) return sortedRows.value
	const result: Row<T>[] = []
	return (function traverse(rows: Row<T>[]) {
		for (const row of rows) {
			result.push(row)
			if (isExpanded(row.key)) traverse(row.children)
		}
		return result
	})(sortedRows.value)
})

//----------------------------------------------------------------------------
// Hide data too big
// This is the final data source for display.

const visibleRows = computed(() => {
	if (expandedRows.value.length <= 1000) return expandedRows.value
	return expandedRows.value.slice(0, 1000)
})

//============================================================================
// Miscellaneous processing not directly related to data
//============================================================================

//----------------------------------------------------------------------------
// Enabled

const enabled = useEnabled()

//----------------------------------------------------------------------------
// Column reordering

const visibleColumnsProp = defineModel<ColumnID[]>('visibleColumns')
const visibleColumns = computed<ColumnID[]>(() =>
	visibleColumnsProp.value ?? Object.keys(props.view.columns) as ColumnID[])

//----------------------------------------------------------------------------
// Column resizing

const columnWidth = ref<{ [id in ColumnID]?: number }>({})
const gridTemplateColumns = computed(() => visibleColumns.value.map(id =>
	(columnWidth.value[id] ?? props.view.columns[id].initialWidth) + 'px'
).join(' '))

//----------------------------------------------------------------------------
// Selection

const modelValue = defineModel<number>({ default: 0 }) // currentIndex
const selectionStart = ref(2)
const selectionEnd = ref(4)
</script>

<template>
	<div :class="{
		'list-view': true,
		tree: view.getChildren,
	}">
		<input type="text" ref="filterInput" v-model="filter" />
		<table :style="{
			gridTemplateColumns,
		}" @mousedown.left.prevent="filterInput?.focus()" :inert="!enabled">
			<thead>
				<tr :class="{
					expanded: expandedInverted,
				}">
					<th v-for="columnID in visibleColumns" :key="columnID" :class="{
						ascending: sortingMap[columnID]?.clause.descending === false,
						descending: sortingMap[columnID]?.clause.descending === true,
					}" :data-sort-order="sortingMap[columnID]?.order" @click="
						($event.target as HTMLElement).classList.contains('grip')
						|| clickHeader(columnID, $event.ctrlKey || $event.metaKey)">
						<span>{{ view.columns[columnID].name }}</span>
						<Grip :x="columnWidth[columnID] ?? view.columns[columnID].initialWidth" :min-x="0" @input="// @ts-expect-error weird error caused by ColumnID
							x => columnWidth[columnID] = x" />
					</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="(row, i) in visibleRows" :key="row.key" :class="{
					current: i === modelValue,
					selected: i >= selectionStart && i < selectionEnd,
					expandable: row.children.length,
					expanded: row.children.length && isExpanded(row.key),
				}" :style="{
					'--indent': row.indent,
				}" @click="toggleExpanded(row.key)">
					<td v-for="columnID in visibleColumns" :key="columnID">
						<component :is="view.columns[columnID].render" :item="row.item" />
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<style lang="scss">
.list-view {
	flex-direction: column;

	>table {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		flex: 1;
		overflow: auto;
		grid: 1lh / auto-flow;

		>thead,
		>tbody {
			display: block;
			grid: inherit;

			>tr {
				display: grid;
				grid: inherit;
				contain: strict;
				content-visibility: auto;
			}
		}

		>thead {
			position: sticky;
			top: 0;
			z-index: 1;
		}

		>thead>tr>th {
			display: flex;

			>span {
				flex: 1;
			}

			>.grip {
				cursor: col-resize;
				touch-action: none;
			}
		}

		>thead>tr>th>span,
		>tbody>tr>td {
			white-space: nowrap;
			overflow: hidden;
			text-overflow: ellipsis;
		}
	}
}
</style>
